//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 17.05.2018 11:08:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace FhooeContext
{

    [DatabaseAttribute(Name = "fhooe")]
    [ProviderAttribute(typeof(Devart.Data.MySql.Linq.Provider.MySqlDataProvider))]
    public partial class FhooeDataContext : Devart.Data.Linq.DataContext
    {
        public static CompiledQueryCache compiledQueryCache = CompiledQueryCache.RegisterDataContext(typeof(FhooeDataContext));
        private static MappingSource mappingSource = new Devart.Data.Linq.Mapping.AttributeMappingSource();

        #region Extensibility Method Definitions
    
        partial void OnCreated();
        partial void OnSubmitError(Devart.Data.Linq.SubmitErrorEventArgs args);
        partial void InsertAppointment(Appointment instance);
        partial void UpdateAppointment(Appointment instance);
        partial void DeleteAppointment(Appointment instance);
        partial void InsertPerson(Person instance);
        partial void UpdatePerson(Person instance);
        partial void DeletePerson(Person instance);
        partial void InsertRoom(Room instance);
        partial void UpdateRoom(Room instance);
        partial void DeleteRoom(Room instance);
        partial void InsertStudyprogram(Studyprogram instance);
        partial void UpdateStudyprogram(Studyprogram instance);
        partial void DeleteStudyprogram(Studyprogram instance);
        partial void InsertTeacher(Teacher instance);
        partial void UpdateTeacher(Teacher instance);
        partial void DeleteTeacher(Teacher instance);

        #endregion

        public FhooeDataContext() :
        base(GetConnectionString("FhooeDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        public FhooeDataContext(MappingSource mappingSource) :
        base(GetConnectionString("FhooeDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        private static string GetConnectionString(string connectionStringName)
        {
            System.Configuration.ConnectionStringSettings connectionStringSettings = System.Configuration.ConfigurationManager.ConnectionStrings[connectionStringName];
            if (connectionStringSettings == null)
                throw new InvalidOperationException("Connection string \"" + connectionStringName +"\" could not be found in the configuration file.");
            return connectionStringSettings.ConnectionString;
        }

        public FhooeDataContext(string connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public FhooeDataContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public FhooeDataContext(string connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public FhooeDataContext(System.Data.IDbConnection connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
          OnCreated();
        }

        public Devart.Data.Linq.Table<Appointment> Appointments
        {
            get
            {
                return this.GetTable<Appointment>();
            }
        }

        public Devart.Data.Linq.Table<Person> People
        {
            get
            {
                return this.GetTable<Person>();
            }
        }

        public Devart.Data.Linq.Table<Room> Rooms
        {
            get
            {
                return this.GetTable<Room>();
            }
        }

        public Devart.Data.Linq.Table<Studyprogram> Studyprograms
        {
            get
            {
                return this.GetTable<Studyprogram>();
            }
        }

        public Devart.Data.Linq.Table<Teacher> Teachers
        {
            get
            {
                return this.GetTable<Teacher>();
            }
        }
    }
}

namespace FhooeContext
{

    /// <summary>
    /// There are no comments for FhooeContext.Appointment in the schema.
    /// </summary>
    [Table(Name = @"fhooe.appointment")]
    public partial class Appointment : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _ID;

        private System.Nullable<int> _SemesterNumber;

        private string _SemesterName;

        private System.DateTime _Beginning;

        private System.DateTime _Ending;

        private string _Type;

        private string _Identification;

        private System.Nullable<int> _Teacher;

        private System.Nullable<int> _Room;

        private System.Nullable<int> _StudyProgram;
        #pragma warning restore 0649

        private EntityRef<Teacher> _Teacher1;

        private EntityRef<Studyprogram> _Studyprogram;

        private EntityRef<Room> _Room1;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        partial void OnSemesterNumberChanging(System.Nullable<int> value);
        partial void OnSemesterNumberChanged();
        partial void OnSemesterNameChanging(string value);
        partial void OnSemesterNameChanged();
        partial void OnBeginningChanging(System.DateTime value);
        partial void OnBeginningChanged();
        partial void OnEndingChanging(System.DateTime value);
        partial void OnEndingChanged();
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        partial void OnIdentificationChanging(string value);
        partial void OnIdentificationChanged();
        partial void OnTeacherChanging(System.Nullable<int> value);
        partial void OnTeacherChanged();
        partial void OnRoomChanging(System.Nullable<int> value);
        partial void OnRoomChanged();
        partial void OnStudyProgramChanging(System.Nullable<int> value);
        partial void OnStudyProgramChanged();
        #endregion

        public Appointment()
        {
            this._Teacher1  = default(EntityRef<Teacher>);
            this._Studyprogram  = default(EntityRef<Studyprogram>);
            this._Room1  = default(EntityRef<Room>);
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ID in the schema.
        /// </summary>
        [Column(Storage = "_ID", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT(11) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                if (this._ID != value)
                {
                    this.OnIDChanging(value);
                    this.SendPropertyChanging();
                    this._ID = value;
                    this.SendPropertyChanged("ID");
                    this.OnIDChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for SemesterNumber in the schema.
        /// </summary>
        [Column(Name = @"semesterNumber", Storage = "_SemesterNumber", DbType = "INT(2) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> SemesterNumber
        {
            get
            {
                return this._SemesterNumber;
            }
            set
            {
                if (this._SemesterNumber != value)
                {
                    this.OnSemesterNumberChanging(value);
                    this.SendPropertyChanging();
                    this._SemesterNumber = value;
                    this.SendPropertyChanged("SemesterNumber");
                    this.OnSemesterNumberChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for SemesterName in the schema.
        /// </summary>
        [Column(Name = @"semesterName", Storage = "_SemesterName", DbType = "VARCHAR(20) NULL", UpdateCheck = UpdateCheck.Never)]
        public string SemesterName
        {
            get
            {
                return this._SemesterName;
            }
            set
            {
                if (this._SemesterName != value)
                {
                    this.OnSemesterNameChanging(value);
                    this.SendPropertyChanging();
                    this._SemesterName = value;
                    this.SendPropertyChanged("SemesterName");
                    this.OnSemesterNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Beginning in the schema.
        /// </summary>
        [Column(Name = @"beginning", Storage = "_Beginning", CanBeNull = false, DbType = "DATETIME NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime Beginning
        {
            get
            {
                return this._Beginning;
            }
            set
            {
                if (this._Beginning != value)
                {
                    this.OnBeginningChanging(value);
                    this.SendPropertyChanging();
                    this._Beginning = value;
                    this.SendPropertyChanged("Beginning");
                    this.OnBeginningChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Ending in the schema.
        /// </summary>
        [Column(Name = @"ending", Storage = "_Ending", CanBeNull = false, DbType = "DATETIME NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime Ending
        {
            get
            {
                return this._Ending;
            }
            set
            {
                if (this._Ending != value)
                {
                    this.OnEndingChanging(value);
                    this.SendPropertyChanging();
                    this._Ending = value;
                    this.SendPropertyChanged("Ending");
                    this.OnEndingChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Type in the schema.
        /// </summary>
        [Column(Name = @"type", Storage = "_Type", DbType = "VARCHAR(50) NULL", UpdateCheck = UpdateCheck.Never)]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                if (this._Type != value)
                {
                    this.OnTypeChanging(value);
                    this.SendPropertyChanging();
                    this._Type = value;
                    this.SendPropertyChanged("Type");
                    this.OnTypeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Identification in the schema.
        /// </summary>
        [Column(Name = @"identification", Storage = "_Identification", DbType = "VARCHAR(50) NULL", UpdateCheck = UpdateCheck.Never)]
        public string Identification
        {
            get
            {
                return this._Identification;
            }
            set
            {
                if (this._Identification != value)
                {
                    this.OnIdentificationChanging(value);
                    this.SendPropertyChanging();
                    this._Identification = value;
                    this.SendPropertyChanged("Identification");
                    this.OnIdentificationChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Teacher in the schema.
        /// </summary>
        [Column(Name = @"teacher", Storage = "_Teacher", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> Teacher
        {
            get
            {
                return this._Teacher;
            }
            set
            {
                if (this._Teacher != value)
                {
                    if (this._Teacher1.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnTeacherChanging(value);
                    this.SendPropertyChanging();
                    this._Teacher = value;
                    this.SendPropertyChanged("Teacher");
                    this.OnTeacherChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Room in the schema.
        /// </summary>
        [Column(Name = @"room", Storage = "_Room", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> Room
        {
            get
            {
                return this._Room;
            }
            set
            {
                if (this._Room != value)
                {
                    if (this._Room1.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnRoomChanging(value);
                    this.SendPropertyChanging();
                    this._Room = value;
                    this.SendPropertyChanged("Room");
                    this.OnRoomChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for StudyProgram in the schema.
        /// </summary>
        [Column(Name = @"studyProgram", Storage = "_StudyProgram", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> StudyProgram
        {
            get
            {
                return this._StudyProgram;
            }
            set
            {
                if (this._StudyProgram != value)
                {
                    if (this._Studyprogram.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnStudyProgramChanging(value);
                    this.SendPropertyChanging();
                    this._StudyProgram = value;
                    this.SendPropertyChanged("StudyProgram");
                    this.OnStudyProgramChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Teacher1 in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Teacher_Appointment", Storage="_Teacher1", ThisKey="Teacher", OtherKey="ID", IsForeignKey=true)]
        public Teacher Teacher1
        {
            get
            {
                return this._Teacher1.Entity;
            }
            set
            {
                Teacher previousValue = this._Teacher1.Entity;
                if ((previousValue != value) || (this._Teacher1.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Teacher1.Entity = null;
                        previousValue.Appointments.Remove(this);
                    }
                    this._Teacher1.Entity = value;
                    if (value != null)
                    {
                        this._Teacher = value.ID;
                        value.Appointments.Add(this);
                    }
                    else
                    {
                        this._Teacher = default(System.Nullable<int>);
                    }
                    this.SendPropertyChanged("Teacher1");
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Studyprogram in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Studyprogram_Appointment", Storage="_Studyprogram", ThisKey="StudyProgram", OtherKey="ID", IsForeignKey=true)]
        public Studyprogram Studyprogram
        {
            get
            {
                return this._Studyprogram.Entity;
            }
            set
            {
                Studyprogram previousValue = this._Studyprogram.Entity;
                if ((previousValue != value) || (this._Studyprogram.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Studyprogram.Entity = null;
                        previousValue.Appointments.Remove(this);
                    }
                    this._Studyprogram.Entity = value;
                    if (value != null)
                    {
                        this._StudyProgram = value.ID;
                        value.Appointments.Add(this);
                    }
                    else
                    {
                        this._StudyProgram = default(System.Nullable<int>);
                    }
                    this.SendPropertyChanged("Studyprogram");
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Room1 in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Room_Appointment", Storage="_Room1", ThisKey="Room", OtherKey="ID", IsForeignKey=true)]
        public Room Room1
        {
            get
            {
                return this._Room1.Entity;
            }
            set
            {
                Room previousValue = this._Room1.Entity;
                if ((previousValue != value) || (this._Room1.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging();
                    if (previousValue != null)
                    {
                        this._Room1.Entity = null;
                        previousValue.Appointments.Remove(this);
                    }
                    this._Room1.Entity = value;
                    if (value != null)
                    {
                        this._Room = value.ID;
                        value.Appointments.Add(this);
                    }
                    else
                    {
                        this._Room = default(System.Nullable<int>);
                    }
                    this.SendPropertyChanged("Room1");
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for FhooeContext.Person in the schema.
    /// </summary>
    [Table(Name = @"fhooe.person")]
    public partial class Person : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _PersonID;

        private string _Vorname;

        private string _Nachname;

        private int _SVNR;
        #pragma warning restore 0649
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnPersonIDChanging(int value);
        partial void OnPersonIDChanged();
        partial void OnVornameChanging(string value);
        partial void OnVornameChanged();
        partial void OnNachnameChanging(string value);
        partial void OnNachnameChanged();
        partial void OnSVNRChanging(int value);
        partial void OnSVNRChanged();
        #endregion

        public Person()
        {
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for PersonID in the schema.
        /// </summary>
        [Column(Name = @"personID", Storage = "_PersonID", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT(11) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public int PersonID
        {
            get
            {
                return this._PersonID;
            }
            set
            {
                if (this._PersonID != value)
                {
                    this.OnPersonIDChanging(value);
                    this.SendPropertyChanging();
                    this._PersonID = value;
                    this.SendPropertyChanged("PersonID");
                    this.OnPersonIDChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Vorname in the schema.
        /// </summary>
        [Column(Storage = "_Vorname", CanBeNull = false, DbType = "VARCHAR(30) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Vorname
        {
            get
            {
                return this._Vorname;
            }
            set
            {
                if (this._Vorname != value)
                {
                    this.OnVornameChanging(value);
                    this.SendPropertyChanging();
                    this._Vorname = value;
                    this.SendPropertyChanged("Vorname");
                    this.OnVornameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Nachname in the schema.
        /// </summary>
        [Column(Storage = "_Nachname", CanBeNull = false, DbType = "VARCHAR(30) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Nachname
        {
            get
            {
                return this._Nachname;
            }
            set
            {
                if (this._Nachname != value)
                {
                    this.OnNachnameChanging(value);
                    this.SendPropertyChanging();
                    this._Nachname = value;
                    this.SendPropertyChanged("Nachname");
                    this.OnNachnameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for SVNR in the schema.
        /// </summary>
        [Column(Storage = "_SVNR", CanBeNull = false, DbType = "INT(11) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int SVNR
        {
            get
            {
                return this._SVNR;
            }
            set
            {
                if (this._SVNR != value)
                {
                    this.OnSVNRChanging(value);
                    this.SendPropertyChanging();
                    this._SVNR = value;
                    this.SendPropertyChanged("SVNR");
                    this.OnSVNRChanged();
                }
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for FhooeContext.Room in the schema.
    /// </summary>
    [Table(Name = @"fhooe.room")]
    public partial class Room : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _ID;

        private string _Building;

        private string _Type;

        private string _RoomName;
        #pragma warning restore 0649

        private EntitySet<Appointment> _Appointments;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        partial void OnBuildingChanging(string value);
        partial void OnBuildingChanged();
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        partial void OnRoomNameChanging(string value);
        partial void OnRoomNameChanged();
        #endregion

        public Room()
        {
            this._Appointments = new EntitySet<Appointment>(new Action<Appointment>(this.attach_Appointments), new Action<Appointment>(this.detach_Appointments));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ID in the schema.
        /// </summary>
        [Column(Storage = "_ID", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT(11) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                if (this._ID != value)
                {
                    this.OnIDChanging(value);
                    this.SendPropertyChanging();
                    this._ID = value;
                    this.SendPropertyChanged("ID");
                    this.OnIDChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Building in the schema.
        /// </summary>
        [Column(Name = @"building", Storage = "_Building", CanBeNull = false, DbType = "VARCHAR(10) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Building
        {
            get
            {
                return this._Building;
            }
            set
            {
                if (this._Building != value)
                {
                    this.OnBuildingChanging(value);
                    this.SendPropertyChanging();
                    this._Building = value;
                    this.SendPropertyChanged("Building");
                    this.OnBuildingChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Type in the schema.
        /// </summary>
        [Column(Name = @"type", Storage = "_Type", CanBeNull = false, DbType = "VARCHAR(10) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                if (this._Type != value)
                {
                    this.OnTypeChanging(value);
                    this.SendPropertyChanging();
                    this._Type = value;
                    this.SendPropertyChanged("Type");
                    this.OnTypeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for RoomName in the schema.
        /// </summary>
        [Column(Name = @"roomName", Storage = "_RoomName", CanBeNull = false, DbType = "VARCHAR(50) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string RoomName
        {
            get
            {
                return this._RoomName;
            }
            set
            {
                if (this._RoomName != value)
                {
                    this.OnRoomNameChanging(value);
                    this.SendPropertyChanging();
                    this._RoomName = value;
                    this.SendPropertyChanged("RoomName");
                    this.OnRoomNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Appointments in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Room_Appointment", Storage="_Appointments", ThisKey="ID", OtherKey="Room", DeleteRule="CASCADE")]
        public EntitySet<Appointment> Appointments
        {
            get
            {
                return this._Appointments;
            }
            set
            {
                this._Appointments.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Appointments(Appointment entity)
        {
            this.SendPropertyChanging("Appointments");
            entity.Room1 = this;
        }
    
        private void detach_Appointments(Appointment entity)
        {
            this.SendPropertyChanging("Appointments");
            entity.Room1 = null;
        }
    }

    /// <summary>
    /// There are no comments for FhooeContext.Studyprogram in the schema.
    /// </summary>
    [Table(Name = @"fhooe.studyprogram")]
    public partial class Studyprogram : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _ID;

        private string _ProgramName;

        private int _ProgramNumber;

        private string _ProgramGraduate;

        private string _ProgramType;
        #pragma warning restore 0649

        private EntitySet<Appointment> _Appointments;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        partial void OnProgramNameChanging(string value);
        partial void OnProgramNameChanged();
        partial void OnProgramNumberChanging(int value);
        partial void OnProgramNumberChanged();
        partial void OnProgramGraduateChanging(string value);
        partial void OnProgramGraduateChanged();
        partial void OnProgramTypeChanging(string value);
        partial void OnProgramTypeChanged();
        #endregion

        public Studyprogram()
        {
            this._Appointments = new EntitySet<Appointment>(new Action<Appointment>(this.attach_Appointments), new Action<Appointment>(this.detach_Appointments));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ID in the schema.
        /// </summary>
        [Column(Storage = "_ID", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT(11) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                if (this._ID != value)
                {
                    this.OnIDChanging(value);
                    this.SendPropertyChanging();
                    this._ID = value;
                    this.SendPropertyChanged("ID");
                    this.OnIDChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ProgramName in the schema.
        /// </summary>
        [Column(Name = @"programName", Storage = "_ProgramName", CanBeNull = false, DbType = "VARCHAR(50) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string ProgramName
        {
            get
            {
                return this._ProgramName;
            }
            set
            {
                if (this._ProgramName != value)
                {
                    this.OnProgramNameChanging(value);
                    this.SendPropertyChanging();
                    this._ProgramName = value;
                    this.SendPropertyChanged("ProgramName");
                    this.OnProgramNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ProgramNumber in the schema.
        /// </summary>
        [Column(Name = @"programNumber", Storage = "_ProgramNumber", CanBeNull = false, DbType = "INT(5) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int ProgramNumber
        {
            get
            {
                return this._ProgramNumber;
            }
            set
            {
                if (this._ProgramNumber != value)
                {
                    this.OnProgramNumberChanging(value);
                    this.SendPropertyChanging();
                    this._ProgramNumber = value;
                    this.SendPropertyChanged("ProgramNumber");
                    this.OnProgramNumberChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ProgramGraduate in the schema.
        /// </summary>
        [Column(Name = @"programGraduate", Storage = "_ProgramGraduate", DbType = "VARCHAR(20) NULL", UpdateCheck = UpdateCheck.Never)]
        public string ProgramGraduate
        {
            get
            {
                return this._ProgramGraduate;
            }
            set
            {
                if (this._ProgramGraduate != value)
                {
                    this.OnProgramGraduateChanging(value);
                    this.SendPropertyChanging();
                    this._ProgramGraduate = value;
                    this.SendPropertyChanged("ProgramGraduate");
                    this.OnProgramGraduateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ProgramType in the schema.
        /// </summary>
        [Column(Name = @"programType", Storage = "_ProgramType", DbType = "VARCHAR(50) NULL", UpdateCheck = UpdateCheck.Never)]
        public string ProgramType
        {
            get
            {
                return this._ProgramType;
            }
            set
            {
                if (this._ProgramType != value)
                {
                    this.OnProgramTypeChanging(value);
                    this.SendPropertyChanging();
                    this._ProgramType = value;
                    this.SendPropertyChanged("ProgramType");
                    this.OnProgramTypeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Appointments in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Studyprogram_Appointment", Storage="_Appointments", ThisKey="ID", OtherKey="StudyProgram", DeleteRule="CASCADE")]
        public EntitySet<Appointment> Appointments
        {
            get
            {
                return this._Appointments;
            }
            set
            {
                this._Appointments.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Appointments(Appointment entity)
        {
            this.SendPropertyChanging("Appointments");
            entity.Studyprogram = this;
        }
    
        private void detach_Appointments(Appointment entity)
        {
            this.SendPropertyChanging("Appointments");
            entity.Studyprogram = null;
        }
    }

    /// <summary>
    /// There are no comments for FhooeContext.Teacher in the schema.
    /// </summary>
    [Table(Name = @"fhooe.teacher")]
    public partial class Teacher : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _ID;

        private string _FirstName;

        private string _LastName;
        #pragma warning restore 0649

        private EntitySet<Appointment> _Appointments;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        #endregion

        public Teacher()
        {
            this._Appointments = new EntitySet<Appointment>(new Action<Appointment>(this.attach_Appointments), new Action<Appointment>(this.detach_Appointments));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ID in the schema.
        /// </summary>
        [Column(Storage = "_ID", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "INT(11) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                if (this._ID != value)
                {
                    this.OnIDChanging(value);
                    this.SendPropertyChanging();
                    this._ID = value;
                    this.SendPropertyChanged("ID");
                    this.OnIDChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for FirstName in the schema.
        /// </summary>
        [Column(Name = @"firstName", Storage = "_FirstName", CanBeNull = false, DbType = "VARCHAR(50) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                if (this._FirstName != value)
                {
                    this.OnFirstNameChanging(value);
                    this.SendPropertyChanging();
                    this._FirstName = value;
                    this.SendPropertyChanged("FirstName");
                    this.OnFirstNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for LastName in the schema.
        /// </summary>
        [Column(Name = @"lastName", Storage = "_LastName", CanBeNull = false, DbType = "VARCHAR(50) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                if (this._LastName != value)
                {
                    this.OnLastNameChanging(value);
                    this.SendPropertyChanging();
                    this._LastName = value;
                    this.SendPropertyChanged("LastName");
                    this.OnLastNameChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Appointments in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="Teacher_Appointment", Storage="_Appointments", ThisKey="ID", OtherKey="Teacher", DeleteRule="CASCADE")]
        public EntitySet<Appointment> Appointments
        {
            get
            {
                return this._Appointments;
            }
            set
            {
                this._Appointments.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Appointments(Appointment entity)
        {
            this.SendPropertyChanging("Appointments");
            entity.Teacher1 = this;
        }
    
        private void detach_Appointments(Appointment entity)
        {
            this.SendPropertyChanging("Appointments");
            entity.Teacher1 = null;
        }
    }

}
